name: Build and Test

on:
  push:
    branches: [ main ] # Trigger on pushes to the main branch
  pull_request:
    branches: [ main ] # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checkout your repository code

      - name: Set up CMake
        uses: jwlawrence/cmake-github-actions@v1 # Use a CMake setup action
        with:
          cmake_version: '3.25' # Or specify a version

      - name: Configure CMake
        run: cmake -B build -S . # Configure the build directory

      - name: Build
        run: cmake --build build # Build the project

      - name: Run tests (if applicable)
        run: cd build && ctest # Run CTest tests from the build directory

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v3
        with:
          name: my-build-artifact
          path: build/myprogram # Path to your executable or other artifacts

      - name: Deploy (optional)
        if: github.ref == 'refs/heads/main' # Only deploy on pushes to main
        # Add your deployment steps here (e.g., to a server or cloud platform)
        run: echo "Deploying..." # Placeholder for deployment commands
