# GitHub Actions workflow for building and testing Box3D.

name: Build and Test

# Triggers the workflow on pushes and pull requests to the main branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Sets the build type environment variable. Defaults to Debug.
env:
  BUILD_TYPE: Debug

# Defines the jobs to run.
jobs:
 
 # Build job for macOS.
  build-macos:
    name: macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBOX2D_SAMPLES=OFF -DBOX2D_SANITIZE=ON -DBUILD_SHARED_LIBS=OFF -DBOX2D_VALIDATE=ON
        # -DBOX2D_SANITIZE=ON: Enables address sanitizer for memory error detection.
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ./bin/test

 # Build job for macOS samples (Release build).
  samples-macos:
    name: samples-macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DBOX2D_SAMPLES=ON -DBUILD_SHARED_LIBS=OFF -DBOX2D_UNIT_TESTS=OFF
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release
