name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install autoconf and automake  # Install build tools
        run: sudo apt-get update && sudo apt-get install -y autoconf automake

      - name: Generate configure script   # Run autoconf (and related tools)
        run: |
          autoreconf -i # or autoconf if autoreconf is not available.

      - name: Configure
        run: ./configure

      - name: Make
        run: make

      - name: Make Check
        run: make check

      - name: Make Distcheck
        run: make distcheck
